ll:
	g++ Codes/ll.cpp -o Executables/ll.exe 

firstfollow:
	g++ Codes/firstfollow.cpp -o Executables/firstfollow.exe 

parser:
	g++ Codes/parser.cpp -o Executables/parser.exe 

run:
	$(MAKE) ll
	$(MAKE) firstfollow
	$(MAKE) parser
